name = "AtomicAndPhysicalConstants"
uuid = "5c0d271c-5419-4163-b387-496237733d8b"
authors = ["David Sagan <david.sagan@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
